# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8e56f2c1-2c39-432b-b4f9-94dbb1e01adc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8e56f2c1-2c39-432b-b4f9-94dbb1e01adc".device = "/dev/disk/by-uuid/8e56f2c1-2c39-432b-b4f9-94dbb1e01adc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3F19-D388";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fe1352d0-c036-4037-91e5-e6c5d42b4845"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
